baseURL = "https://expectation.management/"
languageCode = "en-gb"
title = "Expectation Management"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Matt Berryman"
    description = "by Matt Berryman"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:hello@mattberryman.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/mattberryman/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/mattberryman/"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/mattberryman/"
    name = "fab fa-linkedin"
    weight = 4
